"""add_platform_identity

Revision ID: 156b17080a2e
Revises: a1b2c3d4e5f6
Create Date: 2026-05-22 18:16:29.631115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156b17080a2e'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_usage_events', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_llm_usage_events_user_id'), 'llm_usage_events', type_='foreignkey')
    op.create_foreign_key(None, 'llm_usage_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('readings', 'spread_type',
               existing_type=sa.VARCHAR(length=64),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('readings', 'spread_type',
               existing_type=sa.VARCHAR(length=64),
               server_default=sa.text("'3_cards'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'llm_usage_events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_llm_usage_events_user_id'), 'llm_usage_events', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('llm_usage_events', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
